name: uncertain
version: 1.5.0.9

dependencies:
  - base

library:
  exposed-modules: Uncertain
  source-dirs: src
  ghc-options: -Wall -Wunused-top-binds
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.